version: "3"
services:
  dst-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: dst-bot:${IMAGE_TAG:-latest}
    restart: always
    environment:
      - NAPCAT_API=http://napcat:3000
      - DATABASE_URL=sqlite:/app/data/bot.sqlite3
      - KLEI_TOKEN=pds-g^KU_QSHhEciD^XZusQbOd+Sh0wX0oMQ/n8uSXQkfN8/QLMBJrdNx5nIU=
    volumes:
      - ${PWD}/data/dst-bot:/app/data
    ports:
      - "8001:8000"
  napcat:
    container_name: napcat
    image: mlikiowa/napcat-docker:latest
    restart: always
    environment:
      - ACCOUNT=1811992125
      - HTTP_ENABLE=true
      - HTTP_POST_ENABLE=true
      - HTTP_URLS=["http://dst-bot:8000/event"]
    volumes:
      - ${PWD}/data/napcat/qq:/root/.config/QQ
