version: "3"
services:
  dst-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: dst-bot:${IMAGE_TAG:-latest}
    restart: always
    environment:
      - ACCOUNT=${ACCOUNT:-机器人QQ号}
      - KLEI_TOKEN=${KLEI_TOKEN:-科雷令牌}
      - WENDY_API=${WENDY_API:-}
      - NAPCAT_API=http://napcat:3000
      - DATABASE_URL=sqlite:/app/data/bot.sqlite3
    volumes:
      - ${PWD}/data/dst-bot:/app/data
    ports:
      - "8001:8000"
  napcat:
    container_name: napcat
    image: mlikiowa/napcat-docker:latest
    restart: always
    environment:
      - ACCOUNT=${ACCOUNT:-机器人QQ号}
      - HTTP_ENABLE=true
      - HTTP_POST_ENABLE=true
      - HTTP_URLS=["http://dst-bot:8000/event"]
    volumes:
      - ${PWD}/data/napcat/qq:/root/.config/QQ
